[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "aiogram>=3.0.0",
    "aiohttp>=3.8.0",
    "aiosqlite>=0.19.0",
    "asyncpg>=0.29.0",
    "python-dotenv>=1.0.0",
]